[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ivado-labs-assignment"
version = "0.1.0"
dependencies = [
    "scikit-learn",
    "psycopg[binary]",
    "fastapi==0.115.6",
    "starlette==0.41.3",
    "uvicorn==0.32.1",
    "wikipedia-api"
]

[project.optional-dependencies]
dev = [
    "pytest==8.3.4",
    "httpx==0.27.2"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = ["src"]
