[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ivado-labs-assignment"
version = "0.1.0"
dependencies = [
    "scikit-learn",
    "psycopg[binary]",
    "fastapi",
    "uvicorn",
    "wikipedia-api",
    "pytest"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = ["src"]
